//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Jubmoo.rc
//
#define IDB_BACKCARD                    62
#define IDD_ABOUTBOX                    100
#define ID_JM_START                     101
#define ID_JM_JOIN                      102
#define ID_JM_QUIT                      103
#define ID_JM_SETTING                   104
#define ID_JM_INFO                      105
#define ID_JM_HELP                      106
#define ID_JM_ABOUT                     107
#define ID_JM_EXIT                      108
#define IDI_CONTINUE                    109
#define IDI_JUBMOO                      141
#define IDC_POINT                       142
#define IDC_GRASP                       143
#define IDI_HEAD1                       143
#define IDC_CLICK                       144
#define IDI_HEAD2                       144
#define IDI_HEAD3                       145
#define IDI_HEAD4                       146
#define IDI_HEAD5                       147
#define IDI_HEAD6                       148
#define IDD_ABOUT                       148
#define IDD_STARTUP                     149
#define IDD_STARTINGROOM                149
#define IDI_HEAD7                       149
#define IDI_HEAD8                       150
#define IDI_HEAD9                       151
#define IDI_HEAD10                      152
#define IDI_HEAD11                      153
#define IDI_HEAD12                      154
#define IDI_HEAD13                      155
#define IDI_HEAD14                      156
#define IDI_HEAD15                      157
#define IDI_HEAD16                      158
#define IDD_HELP                        163
#define ID_CHATEDIT                     167
#define IDB_ANISTAT                     168
#define IDB_PLAYERLABEL                 169
#define IDI_HEADCOM                     169
#define IDB_PLAYERDETAIL                169
#define IDD_SETTING                     170
#define IDI_NOOFWINNER                  173
#define IDI_NOOFCHUAN                   174
#define IDI_NOOFPIG                     175
#define IDI_NOOFBIGCHUAN                176
#define IDI_NOBODY                      180
#define IDB_NUMBER                      181
#define IDD_INFO                        190
#define IDD_NETSTAT                     191
#define IDD_ENDROUND                    192
#define IDD_ROUNDRESULT                 192
#define IDD_JOIN                        193
#define IDI_ARROWB                      194
#define IDD_FACESELECT                  195
#define IDD_BMPPREVIEW                  196
#define IDI_ONLINE                      197
#define IDI_OFFLINE                     198
#define IDI_POS4                        199
#define IDI_POS2                        200
#define IDI_POS3                        201
#define IDI_POS1                        202
#define IDI_START                       207
#define IDI_EXIT                        208
#define IDI_HELP                        209
#define IDI_INFO                        210
#define IDI_JOIN                        211
#define IDI_QUIT                        212
#define IDI_SETTING                     213
#define IDI_ABOUT                       214
#define IDI_JMCONNECT                   215
#define IDI_JMONLINE                    216
#define IDI_JMOFFLINE                   217
#define IDB_JMLOGO                      218
#define IDI_JMCONNECT1                  218
#define IDB_JMDANCE                     220
#define IDI_HEADCOM4                    246
#define IDI_HEADCOM2                    247
#define IDI_HEADCOM3                    248
#define IDI_HEADCOM1                    249
#define IDB_BIGLOGO                     250
#define IDI_MSGSYSTEM                   264
#define IDI_MSGACTION                   265
#define IDI_HEAD17                      266
#define IDI_HEAD18                      267
#define IDI_HEAD19                      268
#define IDI_HEAD20                      269
#define IDR_SND_MYTURN                  270
#define IDR_SND_SHUFFLE                 271
#define IDR_SND_DISCARD2                272
#define IDR_SND_DISCARD1                273
#define IDR_SND_CRASH                   274
#define IDR_SND_POP                     275
#define IDR_SND_CLAPPING                276
#define IDB_CARD                        279
#define IDC_MY_EMAIL                    1050
#define IDC_MY_HOMEPAGE                 1051
#define IDC_TESTSCORE                   1055
#define IDC_MYIP                        1070
#define IDC_CLIENT1                     1072
#define IDC_CLIENT2                     1073
#define IDC_CLIENT3                     1074
#define IDC_GAMENUM2                    1074
#define IDC_GAMESCORE                   1074
#define IDC_CLIENT4                     1075
#define IDC_BUTTON1                     1075
#define IDC_BARCHART                    1075
#define IDC_RESETCOMPSCORE              1075
#define IDC_CLIENT5                     1076
#define IDC_BUTTON2                     1076
#define IDC_LINECHART                   1076
#define IDC_CLIENT6                     1077
#define IDC_SELECTCARD                  1077
#define IDC_CLIENT7                     1078
#define IDC_SELECTDLG                   1078
#define IDC_SELECTNUM                   1079
#define IDC_STATUS                      1080
#define IDC_SELECTPD                    1080
#define IDC_JOINIP                      1081
#define IDC_SELECTFACE                  1085
#define IDC_RESETSCORE                  1086
#define IDC_NOOFBIGCHUAN                1089
#define IDC_NOOFCHUAN                   1090
#define IDC_NOOFWINNER                  1091
#define IDC_NOOFPIG                     1092
#define IDC_NAME                        1093
#define IDC_SLOT1                       1094
#define IDC_SLOT2                       1095
#define IDC_SLOT3                       1096
#define IDC_SLOT4                       1097
#define IDC_SLOT5                       1098
#define IDC_PORT                        1099
#define IDC_NOOFGAMEPLAY2               1099
#define IDC_OPPONENT1                   1100
#define IDC_OPPONENT2                   1101
#define IDC_OPPONENT3                   1102
#define IDC_OPPONENT4                   1103
#define IDC_USECOOLCTL                  1104
#define IDC_USEFADEBKG                  1105
#define IDC_USECUSTOMBKG                1106
#define IDC_BKGFILE                     1107
#define IDC_CARDFILE                    1108
#define IDC_DLGFILE                     1109
#define IDC_NUMFILE                     1110
#define IDC_PDFILE                      1111
#define IDC_RANDOMBKG                   1112
#define IDC_NOOFGAMEPLAY                1112
#define IDC_PREVIEW                     1113
#define IDC_AIFAST                      1113
#define IDC_DEFPORT                     1114
#define IDC_USESOUND                    1114
#define IDC_ARROWB                      1115
#define IDC_SELECTBKG                   1116
#define IDC_AINORMAL                    1117
#define IDC_HEAD1                       1118
#define IDC_AISLOW                      1118
#define IDC_HEAD2                       1119
#define IDC_ALARMTURN                   1119
#define IDC_HEAD3                       1120
#define IDC_BMPPREVIEW                  1120
#define IDC_HEAD4                       1121
#define IDC_HEAD5                       1122
#define IDC_SCORE1                      1122
#define IDC_HEAD6                       1123
#define IDC_SCORE2                      1123
#define IDC_HEAD7                       1124
#define IDC_ARROWB2                     1124
#define IDC_SCORE3                      1124
#define IDC_HEAD8                       1125
#define IDC_ARROWB3                     1125
#define IDC_SCORE4                      1125
#define IDC_HEAD9                       1126
#define IDC_PICKFAST                    1126
#define IDC_RSCORE1                     1126
#define IDC_HEAD10                      1127
#define IDC_PICKNORMAL                  1127
#define IDC_RSCORE2                     1127
#define IDC_HEAD11                      1128
#define IDC_PICKSLOW                    1128
#define IDC_RSCORE3                     1128
#define IDC_HEAD12                      1129
#define IDC_RSCORE4                     1129
#define IDC_HEAD13                      1130
#define IDC_HEAD14                      1131
#define IDC_GAMENUM                     1131
#define IDC_HEAD15                      1132
#define IDC_SWAPJQ                      1132
#define IDC_HEAD16                      1133
#define IDC_CHART                       1133
#define IDC_MSGID                       1134
#define IDC_HEAD17                      1134
#define IDC_BUILDNO                     1135
#define IDC_BUILDDATE                   1135
#define IDC_HEAD18                      1135
#define IDC_NETLOG                      1136
#define IDC_VERSION                     1136
#define IDC_HEAD19                      1136
#define IDC_DEFCHATMSG                  1137
#define IDC_HEAD20                      1137

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        280
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1138
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
